#KubeJS Dev Properties
#Fri May 08 09:53:14 CEST 2026
logSkippedTags=false
logSkippedRecipes=false
logSkippedPlugins=true
debugInfo=true
strictTags=false
logAddedRecipes=false
logRemovedRecipes=false
logModifiedRecipes=false
logInvalidRecipeHandlers=true
dataPackOutput=false
logGeneratedData=false
logErroringRecipes=true
alwaysCaptureErrors=false
